-- Solo lectura. Guarda el resultado como qa/raw/esquema.txt
select json_build_object(
 'tablas',(select json_agg(json_build_object('t',c.relname,'cols',(select json_agg(json_build_object('n',a.attname,'ty',format_type(a.atttypid,a.atttypmod),'id',a.attidentity,'gen',a.attgenerated,'def',pg_get_expr(d.adbin,d.adrelid),'nn',a.attnotnull) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped))) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'),
 'seqs',(select json_agg(json_build_object('s',s.relname,'v',(select last_value from pg_sequences q where q.schemaname='public' and q.sequencename=s.relname))) from pg_class s join pg_namespace n on n.oid=s.relnamespace where n.nspname='public' and s.relkind='S'),
 'cons',(select json_agg(json_build_object('t',cl.relname,'n',con.conname,'ty',con.contype,'d',pg_get_constraintdef(con.oid))) from pg_constraint con join pg_class cl on cl.oid=con.conrelid join pg_namespace n on n.oid=cl.relnamespace where n.nspname='public' and con.contype in ('p','u','c','f')),
 'idx',(select json_agg(i.indexdef) from pg_indexes i where schemaname='public' and not exists (select 1 from pg_constraint c where c.conname=i.indexname)),
 'views',(select json_agg(json_build_object('v',c.relname,'d',pg_get_viewdef(c.oid))) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='v'),
 'trig',(select json_agg(pg_get_triggerdef(t.oid)) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and not t.tgisinternal),
 'funargs',(select json_agg(json_build_object('n',p.proname,'oid',p.oid,'args',pg_get_function_arguments(p.oid),'ret',pg_get_function_result(p.oid),'set',p.proretset,'argn',p.proargnames,'argt',(select json_agg(format_type(x,null)) from unnest(p.proargtypes) x),'nargs',p.pronargs,'ndef',p.pronargdefaults,'modes',p.proargmodes)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind='f')) j;
