-- Solo lectura. Personal con DNI y nombre cambiados, PIN 1234, sin tokens.
-- Guarda el resultado como qa/raw/chicas.txt
with m0 as (select dni, row_number() over (order by dni) rn from operarios),
m as (select dni, case when dni ~ '^[0-9]{8}$' then '7'||lpad(rn::text,7,'0') else dni end f,
 (array['QUISPE','HUAMAN','FLORES','MAMANI','RAMOS','CHAVEZ','TORRES','VARGAS','ROJAS','CASTILLO','MENDOZA','SALAZAR','GUTIERREZ','PAREDES','CONDORI','ESPINOZA','DIAZ','CRUZ','SANCHEZ','REYES','MORALES','ORTIZ','RIVERA','NUNEZ'])[1+rn%24]||' '||
 (array['SOTO','LEON','PONCE','RIOS','VEGA','CAMPOS','NAVARRO','PALACIOS','AGUILAR','LUNA','CARDENAS','MEDINA','ACOSTA','BRAVO','CORDOVA','FUENTES','HERRERA','LOPEZ'])[1+(rn/24)%18]||', '||
 (array['ANA','ROSA','CARMEN','LUIS','JUAN','MARIA','ELENA','JORGE','LUCIA','PEDRO','SOFIA','MARTHA','CARLOS','GLORIA','DIANA','JOSE','NANCY','RUTH','PAOLA','MIGUEL','KAREN','EDITH','SONIA','RAUL','IRMA','OLGA','TERESA'])[1+rn%27] nom from m0)
select json_build_object(
'operarios',(select json_agg(json_build_object('dni',m.f,'nombres_apellidos',case when o.dni ~ '^[0-9]{8}$' then m.nom else o.nombres_apellidos end,'area_origen',o.area_origen,'area_actual',o.area_actual,'estado',o.estado,'cargo',o.cargo,'pin','1234','categoria',o.categoria,'es_admin',o.es_admin)) from operarios o join m using(dni)),
'asistencia',(select json_agg(json_build_object('id',a.id,'dni',m1.f,'fecha',a.fecha,'estado',a.estado,'registrado_por',coalesce(m2.f,a.registrado_por),'creado',a.creado)) from asistencia a join m m1 on m1.dni=a.dni left join m m2 on m2.dni=a.registrado_por where a.fecha>='2026-08-16'),
'ocurrencias',(select json_agg(json_build_object('id',x.id,'dni',m1.f,'area',x.area,'tipo',x.tipo,'minutos',x.minutos,'detalle',x.detalle,'supervisora_dni',coalesce(m2.f,x.supervisora_dni),'creado',x.creado,'fecha',x.fecha,'hora_salida',x.hora_salida,'hora_retorno',x.hora_retorno,'retorno_confirmado',x.retorno_confirmado)) from ocurrencias x join m m1 on m1.dni=x.dni left join m m2 on m2.dni=x.supervisora_dni),
'solicitudes_ajuste',(select json_agg(json_build_object('id',x.id,'dni',m1.f,'area',x.area,'fecha',x.fecha,'minutos',x.minutos,'motivo',x.motivo,'estado',x.estado,'minutos_final',x.minutos_final,'resuelto_por',m2.f,'resuelto_en',x.resuelto_en,'creado',x.creado,'tipo',x.tipo,'solicitante_dni',m3.f,'solo_ingenieria',x.solo_ingenieria)) from solicitudes_ajuste x join m m1 on m1.dni=x.dni left join m m2 on m2.dni=x.resuelto_por left join m m3 on m3.dni=x.solicitante_dni),
'movimientos_area',(select json_agg(json_build_object('id',x.id,'dni',m1.f,'area_anterior',x.area_anterior,'area_nueva',x.area_nueva,'movido_por',coalesce(m2.f,x.movido_por),'creado',x.creado,'fecha',x.fecha,'origen',x.origen)) from movimientos_area x join m m1 on m1.dni=x.dni left join m m2 on m2.dni=x.movido_por),
'permisos_area',(select json_agg(json_build_object('dni',m1.f,'area',x.area,'nivel',x.nivel,'asignado_por',x.asignado_por,'creado',x.creado)) from permisos_area x join m m1 on m1.dni=x.dni),
'permisos_pestana',(select json_agg(json_build_object('dni',m1.f,'pestana',x.pestana,'asignado_por',x.asignado_por,'creado',x.creado)) from permisos_pestana x join m m1 on m1.dni=x.dni),
'eficiencia_manual',(select json_agg(json_build_object('dni',m1.f,'fecha',x.fecha,'pct',x.pct,'registrado_por',x.registrado_por,'creado',x.creado)) from eficiencia_manual x join m m1 on m1.dni=x.dni),
'bono_modular_override',(select json_agg(json_build_object('dni',m1.f,'desde',x.desde,'hasta',x.hasta,'forzar',x.forzar,'registrado_por',x.registrado_por,'creado',x.creado)) from bono_modular_override x join m m1 on m1.dni=x.dni),
'minutos_consideracion',(select json_agg(json_build_object('id',x.id,'dni',m1.f,'fecha',x.fecha,'minutos',x.minutos,'motivo',x.motivo,'registrado_por',x.registrado_por,'creado',x.creado)) from minutos_consideracion x join m m1 on m1.dni=x.dni),
'area_hora_declarada',(select json_agg(json_build_object('dni',m1.f,'fecha',x.fecha,'area',x.area,'hora',x.hora,'creado',x.creado)) from area_hora_declarada x join m m1 on m1.dni=x.dni),
'boletas_avisos',(select json_agg(json_build_object('dni',m1.f,'fecha',x.fecha,'avisado_por',coalesce(m2.f,x.avisado_por),'creado',x.creado)) from boletas_avisos x join m m1 on m1.dni=x.dni left join m m2 on m2.dni=x.avisado_por),
'areas_config',(select json_agg(t) from areas_config t),'bases_log',(select json_agg(t) from (select id,creado,coalesce(m.f,b.dni) dni,accion,area,articulo,modulo,n_op,operacion,std_antes,std_despues,origen,estudio_id from bases_log b left join m using(dni)) t),
'bono_modular_dia',(select json_agg(t) from bono_modular_dia t),'bono_modular_tabla',(select json_agg(t) from bono_modular_tabla t),'causas_std',(select json_agg(t) from causas_std t),
'estados_asistencia',(select json_agg(t) from estados_asistencia t),'incentivos_tabla',(select json_agg(t) from incentivos_tabla t),'modulos_cerrados',(select json_agg(t) from modulos_cerrados t),
'motivos_cambio_fecha',(select json_agg(t) from motivos_cambio_fecha t),'of_detalle',(select json_agg(t) from of_detalle t),'of_generada',(select json_agg(t) from of_generada t),'of_troceo',(select json_agg(t) from of_troceo t),
'ofs',(select json_agg(t) from ofs t),'operaciones_extra',(select json_agg(t) from operaciones_extra t),'ops_adicionales_of',(select json_agg(t) from ops_adicionales_of t),'residuales',(select json_agg(t) from residuales t),
'sistema_config',(select json_agg(t) from sistema_config t),'tickets_visibilidad',(select json_agg(t) from tickets_visibilidad t),'tiempos_operaciones',(select json_agg(t) from tiempos_operaciones t),'tipos_extra',(select json_agg(t) from tipos_extra t)) j;
